# Generated by Django 5.2.5 on 2025-09-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=175)),
                ('marca', models.CharField(max_length=175)),
                ('modelo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=175)),
            ],
        ),
    ]
