# Generated by Django 5.2.5 on 2025-10-03 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='año',
            new_name='anio',
        ),
    ]
